name: Frontend Deploy to cPanel

on:
  push:
    branches: [ "master" ]

jobs:
  deploy-to-cpanel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies & build
        run: |
          npm install
          npm run build

      - name: Deploy React build to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.CPANEL_FTP_SERVER }}
          username: ${{ secrets.CPANEL_FTP_USERNAME }}
          password: ${{ secrets.CPANEL_FTP_PASSWORD }}
          protocol: ftps
          server-dir: ./
          local-dir: dist/
