name: Frontend Deploy to cPanel

on:
  push:
    branches: ["master"]

jobs:
  deploy-to-cpanel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      # ✅ Proper way to install pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9 # or your project's pnpm version
          run_install: false

      - name: Create .env.production
        run: |
          echo "${{ secrets.APP_ENV }}" >> .env.production

      - name: Install dependencies & build
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Deploy React build to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.CPANEL_FTP_SERVER }}
          username: ${{ secrets.CPANEL_FTP_USERNAME }}
          password: ${{ secrets.CPANEL_FTP_PASSWORD }}
          protocol: ftps
          server-dir: ./
          local-dir: dist/
